config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :orders
  
  resources :posts do
    resources :comments
  end

  get '/pages', to: 'pages#index'
  post '/pages', to: 'pages#create'
  get '/pages/new', to: 'pages#new', as: 'new_page'
  get '/pages/:id', to: 'pages#show', as: 'page'
  get '/pages/:id/edit', to: 'pages#edit', as: 'edit_page'
  patch '/pages/:id', to: 'pages#update'
  delete '/pages/:id', to: 'pages#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/customer.rb
class Customer < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone,  presence: true
  validates :phone, numericality: { only_integer: true }
  validates :phone, length: { is: 10}
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  has_many :orders

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/order.rb
class Order < ApplicationRecord
  validates :product_name, presence: true
  validates :product_count, presence: true
  validates :customer_id, presence: true
  belongs_to :customer
  validates_presence_of :customer
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.create(comment_params)
    redirect_to @post
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to @post
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to @post
  end

  private

  def comment_params
    params.require(:comment).permit(:name,:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  layout 'customer_layout'

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    # @customer = Customer.new(customer_params)
    #
    # respond_to do |format|
    #   if @customer.save
    #     format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
    #     format.json { render :show, status: :created, location: @customer }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @customer.errors, status: :unprocessable_entity }
    #   end
    # end
    @customer = Customer.new(customer_params)
    if @customer.save
      flash.notice = "The customer record was created successfully."
      redirect_to @customer
    else
      flash.now.alert = @customer.errors.full_messages.to_sentence
      render :new
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    # respond_to do |format|
    #   if @customer.update(customer_params)
    #     format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
    #     format.json { render :show, status: :ok, location: @customer }
    #   else
    #     format.html { render :edit }
    #     format.json { render json: @customer.errors, status: :unprocessable_entity }
    #   end
    # end
    if @customer.update(customer_params)
      flash.notice = "The customer record was updated successfully."
      redirect_to @customer
    else
      flash.now.alert = @customer.errors.full_messages.to_sentence
      render :edit
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :phone, :email)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.message
      redirect_to customers_path
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      flash.notice = "The order record was successfully created."
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      flash.notice = "The order record was successfully updated."
      redirect_to order_path(@order)
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    flash.notice = "The order was successfully deleted."
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order).permit(:product_name,:product_count,:customer_id)
  end

  def set_order
    @order=Order.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def index
   @pages = Page.all
 end

 def show
   @page = Page.find(params[:id])
 end

 def new
   @page = Page.new
 end

 def create
   @page = Page.new(page_params)
   @page.save
   redirect_to @page
 end

 def edit
   @page = Page.find(params[:id])
 end

 def update
   @page = Page.find(params[:id])
   @page.update(page_params)
   redirect_to @page
 end

 def destroy
   @page = Page.find(params[:id])
   @page.destroy
   redirect_to pages_path
 end

 private

   def page_params
     params.require(:page).permit(:title,:body,:slug);
   end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div>
  <strong><%= comment.name %> says:</strong>
  <%= comment.content %>
  <div class="comment-admin">
    <%= link_to "Edit", edit_post_comment_path(@post,comment) %>
    <%= link_to "Delete", [@post, comment], method: :delete %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, comment] do |f| %>
<div class="field">
  <%= f.label :name %>
  <%= f.text_field :name %>
<div>
<div class="field">
  <%= f.label :content, "Comment" %>
  <%= f.text_area :content %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>
<%= render partial: "form", locals: {comment: @comment} %>

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
  <% if customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Customers</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Phone</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.full_name %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= link_to 'Show', customer %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer) %></td>
        <td><%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form', customer: @customer %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @customer.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @customer.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>
<% if @customer.orders.any? %>
  <h2>Orders for this customer:</h2>
  <table>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Product Count</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @customer.orders.each do |order| %>
        <tr>
          <td><%= order.product_name %></td>
          <td><%= order.product_count %></td>
          <td><%= link_to 'Show', order %></td>
          <td><%= link_to 'Edit', edit_order_path(order) %></td>
          <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/customer_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if !flash[:alert].nil? %>
      <p class="my_alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order record from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </div>

  <div class="field">
    <%= f.label :product_count %>
    <%= f.text_field :product_count %>
  </div>

  <div class="field">
    <%= f.label :customer_id %>
    <%= f.collection_select :customer_id, Customer.all, :id, :full_name, include_blank: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Product Name</th>
      <th>Product Count</th>
      <th>Customer Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.product_name %></td>
        <td><%= order.product_count %></td>
        <td><%= order.customer.full_name %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @order.product_name %>
</p>

<p>
  <strong>Product count:</strong>
  <%= @order.product_count %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @order.customer.full_name %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/_form.html.erb
<%= form_for(page) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
    <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  
  <div class="field">
    <%= f.label :slug %>
    <%= f.text_field :slug %>
  </div>
  
  <div>
    <%= f.submit %>  
  </div>
<% end %>

app/views/pages/edit.html.erb
<%= render 'form', page: @page %>

app/views/pages/index.html.erb
<h1>Blog Pages</h1>
<% @pages.each do |page| %>
<p><%= link_to page.title, page %></p>
<% end %>
<%= link_to "New Page", new_page_path %>

app/views/pages/new.html.erb
<%= render 'form', page: @page %>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<p><%= @page.body %></p>
<%= link_to "Edit", edit_page_path(@page) %>
<%= link_to "Delete", @page, method: :delete %>

app/views/posts/_form.html.erb
<%= form_for(post) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  
   <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<div id="comments">
  <% if @post.comments.present? %>
  <h1>Comments</h1>
  <% end %>
  <% # @post.comments.each do |comment| %>
    <% #render partial: "comments/comment", locals: {comment: comment} %>
    <% #render partial: "comments/comment", collection: @post.comments, as: :comment %>
    <%= render @post.comments %>
    <h2>Add a comment:</h2>
    <%= render partial: "comments/form", locals: {comment: @post.comments.new} %>
  <% #end %>
</div>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>